version: '3.8'

services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8080:80"
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: Bober2
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Bober2
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: Bober2
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: